name = "HTMLSanitizer"
uuid = "9a15a9f4-ddd5-46ee-89fc-c219f813dd6f"
authors = ["Sebastian Pfitzner"]
version = "0.1.2"

[deps]
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"

[compat]
julia = "1"
Gumbo = "0.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
